spring:
  datasource:
    url: 'jdbc:mysql://localhost:8989/test?serverTimezone=Europe/Berlin&useLegacyDatetimeCode=false'
    username: dev
    password: dev

  application:
    name: 'probe-aufgabe'
  jpa:
    properties:
      hibernate:
        generate_statistics: true 
        order_inserts: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #  ddl-auto: update
      

server:
  port: '8500'
  
management:
  server:
    port: '8500'
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org:
      springframework:
        security: ERROR
        web: ERROR    
      hibernate: ERROR 
        #SQL: DEBUG
        #type: TRACE

  file: logs/